name: Build & SonarCloud (main)

on:
  push:
    branches: [ "main" ]

jobs:
  sonar:
    runs-on: windows-latest
    env:
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_ORG: solanobarcelos
      SONAR_PROJECT_KEY: SolanoBarcelos_ContatoRegistro
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install SonarScanner for .NET
        run: dotnet tool update --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

      - name: Begin SonarCloud analysis
        run: >
          dotnet-sonarscanner begin
          /k:"${{ env.SONAR_PROJECT_KEY }}"
          /o:"${{ env.SONAR_ORG }}"
          /d:sonar.host.url="${{ env.SONAR_HOST_URL }}"
          /d:sonar.token="${{ env.SONAR_TOKEN }}"
          /d:sonar.cs.vstest.reportsPaths="**/*.trx"
          /d:sonar.cs.cobertura.reportsPaths="**/TestResults/**/coverage.cobertura.xml"
          /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"

      - name: Build
        run: dotnet build ContatoRegistro.sln --configuration Release --no-incremental

      - name: Test with coverage (XPlat + runsettings)
        run: >
          dotnet test ContatoRegistro.sln
          --configuration Release
          --logger "trx;LogFileName=test-results.trx"
          --collect "XPlat Code Coverage"
          --settings coverlet.runsettings.xml

      - name: Show coverage files found (debug)
        if: always()
        shell: pwsh
        run: |
          Write-Host "Looking for OpenCover:"
          Get-ChildItem -Recurse -Filter coverage.opencover.xml | % { $_.FullName }
          Write-Host "Looking for Cobertura:"
          Get-ChildItem -Recurse -Filter coverage.cobertura.xml | % { $_.FullName }
          
      # dowload do arquivo de cobertura
      - name: Upload coverage (Cobertura & TRX)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-tests
          path: |
            **/TestResults/**/*.trx
            **/TestResults/**/coverage.cobertura.xml
            **/TestResults/**/coverage.opencover.xml
          if-no-files-found: warn
          retention-days: 7

      - name: End SonarCloud analysis
        run: dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"
