name: Build & SonarCloud (main)

on:
  push:
    branches: [ "main" ]

jobs:
  sonar:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ajuda o Sonar a ler histórico do git

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # SonarCloud precisa de Java 17
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install SonarScanner for .NET
        run: dotnet tool update --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          dotnet-sonarscanner begin
          /k:"<PROJECT_KEY>"
          /o:"<ORG_KEY>"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Build
        run: dotnet build ContatoRegistro.sln --configuration Release --no-incremental

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
