name: Build & SonarCloud (main)

on:
  push:
    branches: [ "main" ]

jobs:
  sonar:
    runs-on: windows-latest
    env:
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_ORG: solanobarcelos
      SONAR_PROJECT_KEY: SolanoBarcelos_ContatoRegistro
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install SonarScanner for .NET
        run: dotnet tool update --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        run: >
          dotnet-sonarscanner begin
          /k:"${{ env.SONAR_PROJECT_KEY }}"
          /o:"${{ env.SONAR_ORG }}"
          /d:sonar.host.url="${{ env.SONAR_HOST_URL }}"
          /d:sonar.token="${{ env.SONAR_TOKEN }}"

      - name: Build
        run: dotnet build ContatoRegistro.sln --configuration Release --no-incremental

      - name: End SonarCloud analysis
        run: dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"

